### ISSUE TITLE
Aufwachladung in Firmware 0827

### ISSUE THREAD

**Issue by ledermann** [solectrus/senec-collector#323]
Nach Installation auf die neue Firmware (Version 0827) kann der Speicher den Status "Aufwachladung" erhalten. Die Darstellung in SOLECTRUS kann dann so aussehen, fälschlicherweise in Orange.

![Aufwachladung](https://github.com/solectrus/senec-collector/assets/3557/f4fcbdbb-dce0-4f36-b39f-984dc7953ce9)

Hier muss ich eine Korrektur vornehmen, sodass auch die Aufwachladung als "OK" erkannt wird und somit grün angezeigt wird. Ich selbst habe die neue Firmware aber noch nicht. Ich kümmere mich darum, sobald ich Näheres weiß.

**Comment by Bart1909** [comment]
Finde den Begriff "Solectronaut" übrigens sehr schön :)
