### ISSUE TITLE
Issue im Senec Collector nach Konfigurationsaenderung

### ISSUE THREAD

**Issue by esusxunil** [solectrus/senec-collector#328]
Hallo zusammen,

ich glaube ich habe meine Installation irgendwie geschrottet und braeuchte einen Denkanstoss.

DuUrch den Umzug in ein anderes Netzwerksegment hat die SENEC Anlage eine neue IP bekommen. Die IP ist auch erreichbar, ich kann z.B. die lokale SENEC Webseite aufrufen.

Um Solectrus die neue IP mitzuteilen, habe ich in der .env Datei des solectrus-senec-collector SENEC_HOST angepasst und den Container dann neu erstellt.

Solectru bleibt aber auf dem Status keine Verbindung und im Log des solectrus-senec-collector finde ich:

Install missing gem executables with `bundle install`
bundler: command not found: app/main.rb

Was mache ich falsch und kann ich nur den Senec collector neu deployen ohne alles neu aufsetzen zu muessen?

**Comment by ledermann** [comment]
Gut, dass du es bereits selber lösen konntest. Der SENEC-Collector wird immer wieder von mir aktualisiert, du hattest vermutlich eine ältere Version. [Aktuell](https://github.com/solectrus/senec-collector/releases) ist momentan `v0.13.1`.

Grundsätzlich ist es immer eine gute Idee, bei Problemen erst mal das hier zu machen, um alles auf den aktuellen Stand zu bringen:

```
cd solectrus
docker compose pull
docker compose up -d
```

Alles neu aufsetzen muss eigentlich nie gemacht werden (Ausnahme: Hardware-Defekte)
