### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by frizzle0815** [solectrus/senec-collector#413]
Ich bekomme seit heute Mittag keine Daten mehr - ohne dass ich irgendetwas geändert hätte.
Die Senec-Cloud ist per App und Web allerdings erreichbar.

Ein Neustart des Containers bringt keine Besserung und zeigt in den Logs folgendes:

```
SENEC collector for SOLECTRUS, Version 0.14.4, built at 2024-07-15T08:39:59.718Z
https://github.com/solectrus/senec-collector
Copyright (c) 2020-2024 Georg Ledermann, released under the MIT License
Using Ruby 3.3.4 on platform x86_64-linux-musl
Pushing to InfluxDB at http://influxdb:8086, bucket solectrus, measurement SENEC
Pulling from SENEC cloud every 300 seconds
No SENEC_SYSTEM_ID given, looking for existing systems...
Found SENEC system xxxx (S1114127808601365943xxxx, de-v3-hd04li10-xxxx)
Using first system, which is xxxx
Error getting data from SENEC cloud: Error 400
Error getting data from SENEC cloud: Error 400
```

**Comment by ledermann** [comment]
Danke für den Hinweis. Ersten Tests zufolge kann ich das reproduzieren. Ich prüfe das genauer...

**Comment by ledermann** [comment]
Es scheint, als wäre nur dieser Endpunkt betroffen:

```
https://app-gateway.prod.senec.dev/v1/senec/systems/{SYSTEM_ID}/technical-data
```

Dieser liefert nun den Fehler `400`, also `Bad request`. Der SENEC-Collector verwendet diesen, um diese Informationen abzurufen:

- Status
- Gehäusetemperatur in °C

Möglicherweise hat SENEC hier Änderungen vorgenommen. Weiß hier jemand etwas?

**Comment by ledermann** [comment]
Oh, aktuell funktioniert es wieder, zumindest bei mir. Der SENEC-Collector bekommt wieder Werte, der Fehler 400 tritt **nicht** mehr auf. Möglicherweise nur Schluckauf bei SENEC.

Wie ist es bei dir, @frizzle0815?

**Comment by frizzle0815** [comment]
Hier läuft es auch wieder 👍
Danke für die schnelle Rückmeldung!

**Comment by ledermann** [comment]
Ok, dann gehe ich erst mal davon aus, dass es ein temporäres Problem bei SENEC war.

Ich schließe das Issue. Falls das Problem wieder auftritt, bitte wieder aufmachen.
