### ISSUE TITLE
Meldung 13 bei Version15.0 15.7.24 nach SENEC Update auf 8828 (LFP Tausch)

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/senec-collector#421]
habe hier für dieses Phänomen die letzten 20 aus der senec-collector log
Anzeige 13 anstatt Akku voll

admin@raspberrypi:/home/pi/solectrus $ sudo docker compose logs senec-collector --tail 20
senec-collector-1  | Got record #2889 at 2024-08-14 16:22:53 +0200 within 8 ms, 13, Inverter 4227 W, House 198 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2889 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #2890 at 2024-08-14 16:22:58 +0200 within 12 ms, 13, Inverter 4219 W, House 205 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2890 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #2891 at 2024-08-14 16:23:03 +0200 within 8 ms, 13, Inverter 4217 W, House 226 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2891 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #2892 at 2024-08-14 16:23:08 +0200 within 16 ms, 13, Inverter 4229 W, House 239 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2892 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #2893 at 2024-08-14 16:23:13 +0200 within 8 ms, 13, Inverter 3788 W, House 199 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2893 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #2894 at 2024-08-14 16:23:18 +0200 within 9 ms, 13, Inverter 4227 W, House 267 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2894 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #2895 at 2024-08-14 16:23:23 +0200 within 7 ms, 13, Inverter 4228 W, House 223 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2895 to InfluxDB
admin@raspberrypi:/home/pi/solectrus $

**Comment by ledermann** [comment]
Die Zahl statt Text liegt an einem fehlenden Mapping. Dieses holt sich der SENEC-Collector beim Start etwas trickreich aus dem JS-Quelltext des Frontend-UI. Möglicherweise geht da etwas schief. Das ist eigentlich gut getestet, daher würde mich das wundern.

Die aktuelle Versionsnummer des SENEC-Collectors ist [0.15.0](https://github.com/solectrus/senec-collector/releases/tag/v0.15.0). Diese muss zwingend installiert sein, sonst funktioniert es nicht. Mit der Version [0.15.0](https://github.com/solectrus/solectrus/releases/tag/v0.15.0), die momentan auch beim Dashboard aktuell ist, hat das **rein gar nichts** zu tun, die Übereinstimmung ist Zufall.

In der `docker-compose.yml` sollte das `latest`-Tag beim SENEC-Collector stehen:

```
image: ghcr.io/solectrus/senec-collector:latest
```

Dein Log-Auszug verrät kaum etwas. Nützlicher wäre es, das Log vom **START** des Containers zu sehen. Daher mache bitte mal Folgendes auf dem betroffen Raspi:

```
docker compose down
docker compose up -d
docker compose logs senec-collector
````

Ich würde gerne die Zeilen von Anfang an (mit Versionsnummer) bis zum ersten "Successfully pushed" sehen.

Meine Vermutung ist: Du hast nicht die aktuelle Version des SENEC-Collectors installiert. Lösung wäre dann `docker compose pull && docker compose up -d`.

**Comment by Zeppelin-PV** [comment]
sorry für die Mühe die ich gemacht habe
docker compose down und compose up -d hat vermutlich schon geholfen
obwohl ich dutzende male compose pull && compose up -d gemacht habe

![grafik](https://github.com/user-attachments/assets/c2ed71eb-b61b-46db-9954-3debdc4e126a)

image: ghcr.io/solectrus/senec-collector:latest  

admin@raspberrypi:/home/pi/solectrus $ sudo docker compose logs senec-collector
senec-collector-1  | SENEC collector for SOLECTRUS, Version 0.15.0, built at 2024-08-06T15:24:33.372Z
senec-collector-1  | https://github.com/solectrus/senec-collector
senec-collector-1  | Copyright (c) 2020-2024 Georg Ledermann, released under the MIT License
senec-collector-1  | 
senec-collector-1  | Using Ruby 3.3.4 on platform aarch64-linux-musl
senec-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement SENEC
senec-collector-1  | 
senec-collector-1  | Pulling from your local SENEC at https://192.168.001.230 every 5 seconds
senec-collector-1  | Getting state names (language: de) from SENEC by parsing source code...
senec-collector-1  | OK, got 101 state names
senec-collector-1  | 
senec-collector-1  | Got record #1 at 2024-08-14 16:55:30 +0200 within 8 ms, AKKU VOLL, Inverter 1126 W, House 472 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #1 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #2 at 2024-08-14 16:55:35 +0200 within 9 ms, AKKU VOLL, Inverter 1115 W, House 452 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #2 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #3 at 2024-08-14 16:55:40 +0200 within 7 ms, AKKU VOLL, Inverter 1109 W, House 431 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #3 to InfluxDB
senec-collector-1  | 
senec-collector-1  | Got record #4 at 2024-08-14 16:55:46 +0200 within 1081 ms, AKKU VOLL, Inverter 1078 W, House 403 W, Wallbox 0 W
senec-collector-1  | Successfully pushed record #4 to InfluxDB

**Comment by ledermann** [comment]
Ok, irgendwas ist bei deinen Update-Versuchen wohl schiefgegangen. Das lässt sich jetzt nicht mehr klären. Aber nun ist ja offenbar als wieder in Ordnung.

**Comment by ledermann** [comment]
Hier eine mögliche Erklärung, was bei dir schiefgelaufen ist:

Du hast oben für den Log-Output `sudo` verwendet. Wenn du mehrere Befehle, die `sudo` erfordern, mit `&&` verknüpfst, aber nur den ersten mit `sudo` beginnst, wird der zweite **nicht** ausgeführt. 

Wenn du also das hier machst:

`sudo docker compose pull && docker compose up -d` 

Dann wird nur der erste Befehl (`docker compose pull` = neue Images herunterladen) ausgeführt, nicht aber der zweite (`docker compose up -d` = neu starten).

Das `sudo` wäre also vor **beiden** Befehlen erforderlich:

`sudo docker compose pull && sudo docker compose up -d` 

Um Probleme dieser Art grundsätzlich zu vermeiden, solltest du den Raspi-User zur Gruppe `docker` hinzufügen, dann ist gar kein `sudo` mehr erforderlich (steht auch in der vom Konfigurator generierten Readme):

```
sudo groupadd docker
sudo usermod -aG docker $USER
```

Siehe https://docs.docker.com/engine/install/linux-postinstall/
