### ISSUE TITLE
Feature Request: Konfigurierbarkeit

### ISSUE THREAD

**Issue by bennysweb** [solectrus/senec-collector#443]
Da ich zusätzlich noch ein Balkonkraftwerk installiert habe, geht der Hausverbrauch tagsüber öfters gen 0 - wird also von Senec und auch von Solectrus nicht korrekt dargestellt (war auch schön öfters Thema hier). Wenn die einzelnen Abfragepunkte konfigurierbar wären, könnte man den Hausverbrauch zB vom MQTT-Collector einsammeln und in das SENEC-Measurement schreiben lassen ohne die historischen Werte zu verlieren. Ebenso wäre das bei der PV-Erzeungung der Fall, da ich hier gern die summierte Erzeugung von beiden Wechselrichtern anzeigen lassen würde. Beide Werte stehen bei mir in HomeAssistant bereit und könnten per MQTT gepusht werden.

**Comment by ledermann** [comment]
Ich denke, das müsste jetzt bereits möglich sein - über die Variable `SENEC_IGNORE`. 

Du würdest also in deine `.env` schreiben:

```env
SENEC_IGNORE=house_power,inverter_power
```

Dann schreibt der SENEC-Collector den Hausverbrauch sowie die Erzeugung nicht mehr in die InfluxDB.

Details hier:
https://github.com/solectrus/senec-collector/wiki/Configuration

Anschließend könntest du den tatsächlichen Hausverbrauch und die summierte Erzeugung per MQTT holen und in die zugehörigen Fields schreiben.

Hilft das?

**Comment by bennysweb** [comment]
Vielen Dank, das hat geholfen. Die Variable hatte ich nicht mehr auf dem Schirm. Jetzt stimmen die Werte mit der Realität überein. Manchmal ist es auch zu einfach... ;-)
